version: "3"
services:
  backend:
    ports:
      - "8000:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: sh -c "python manage.py wait_for_db && python manage.py migrate && python && manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - .:/frontend/nginx.conf:ro
    command: /bin/bash -c "envsubst < /frontend/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80"
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    volumes:
      - evy-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - 5432:5432

volumes:
  evy-db-data:
  evy-static-data:
