version: "3.9"

services:
  backend:
    volumes:
      - static:/static
      - ./backend:/app
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/build
    depends_on:
      - backend


  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
        - "80:80"
    depends_on:
        - backend
        - frontend


  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5430:5432

volumes:
  static:
  frontend:
  dev-db-data:
