# Generated by Django 3.2.18 on 2023-05-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='links',
            field=models.ManyToManyField(to='core.Link'),
        ),
    ]
